#define LBL_ROOM_X_POS          -180
#define LBL_ROOM_Y_POS          -50

#define IMGBTN_AC_X_POS         -150
#define IMGBTN_AC_Y_POS          20

#define IMGBTN_LIGHT_X_POS       0
#define IMGBTN_LIGHT_Y_POS       20

#define IMGBTN_SETTINGS_X_POS    150
#define IMGBTN_SETTINGS_Y_POS    20

#define BTNMATRIX_LIGHTS_X_POS  -90
#define BTNMATRIX_LIGHTS_Y_POS  -15
#define BTNMATRIX_LIGHTS_WIDTH   450
#define BTNMATRIX_LIGHTS_HEIGHT  150

#define SLIDER_BLINDS_WIDTH      30
#define SLIDER_BLINDS_HEIGHT     150
#define SLIDER_BLINDS_X_POS      20
#define SLIDER_BLINDS_Y_POS      25
#define SLIDER_BLINDS_MIN_VALUE  0
#define SLIDER_BLINDS_MAX_VALUE  10

#define BTNMATRIX_SETTINGS_1_WIDTH  200
#define BTNMATRIX_SETTINGS_1_HEIGHT 150

#define BTNMATRIX_SETTINGS_2_WIDTH  190
#define BTNMATRIX_SETTINGS_2_HEIGHT 150
#define BTNMATRIX_SETTINGS_2_X_POS -15
#define BTNMATRIX_SETTINGS_2_Y_POS  10

#define POWER_AC_BTN_X_POS                50
#define POWER_AC_BTN_Y_POS                70

#define DECREASE_TEMP_BTN_X_POS          -150
#define DECREASE_TEMP_BTN_Y_POS          -10

#define INCREASE_TEMP_BTN_X_POS           240
#define INCREASE_TEMP_BTN_Y_POS          -10

#define LBL_SET_TEMP_X_POS               -55
#define LBL_SET_TEMP_Y_POS               -45

#define AC_CONTROL_BNT_SIZE               60

#define BTNMATRIX_EVENT_LIGHTS_ON   0
#define BTNMATRIX_EVENT_LIGHTS_OFF  1
#define BTNMATRIX_EVENT_WORK_SCENE  2
#define BTNMATRIX_EVENT_LUNCH_SCENE 3
#define BTNMATRIX_EVENT_RELAX_SCENE 4
#define BTNMATRIX_EVENT_NIGHT_SCENE 5

#define TEMPERATURE_MIN_VALUE_C 16
#define TEMPERATURE_MAX_VALUE_C 30

#define ROOM_INFO_REFRESH_PERIOD_MS 2000